config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'
require 'admin_constraint'

Masqueunacasa::Application.routes.draw do
  # CONCERNS
  concern :document do
    resource :kudos
  end

  concern :commentable do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  # PARTE SOCIAL
  resources :users, except: [:index]
  resources :groups, except: [:index] do
    resources :memberships, only: [:index, :create, :destroy]
  end

  # GENERAL

  resources :locations, only: [:index]

  match '/entrar' => 'user_sessions#new', as: :login
  match '/salir' => 'user_sessions#destroy', as: :logout
  match '/community' => 'dashboard#community', as: :community
  match '/cuatrocerocuatro' => 'dashboard#cuatrocerocuatro'
  match '/quinientos' => 'dashboard#quinientos'
  match "/enter/:id" => "users#enter", as: :enter
  get '/admin/' => 'dashboard#admin_area', as: :admin_area
  get '/search' => 'searches#show', as: :search

  root to: 'dashboard#welcome'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :password_recoveries

  # HABITAPEDIA

  resources :experiencies, concerns: [:document, :commentable]

  resources :phases, except: [:destroy] do
    resources :categories, except: [:index, :new, :create]
  end

  resources :categories, only: [:show, :new, :create], concerns: [:document, :commentable] do
    resources :proposals, only: [:new]
  end

  resources :proposals, except: [:index, :new], path: '/phases/proposals', concerns: [:document, :commentable] do
    resources :relations, only: [:new, :create, :destroy]
  end

  # ADMINISTRACIÓN

  resources :help_texts, except: [:index]
  resources :help_pages, except: [:index]

  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml', {
    prefix_on_default_locale: true }) # para permitir poner el idioma de la página
                                      # en función de las preferencias del navegador.

  # Rutas para el preview del editor de texto enriquecido
  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"

  # Ruta para la interfaz web de sidekiq
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  # Para dar soporte a las rutas antiguas, que no tenian el parámetro con el locale en
  # el idioma por defecto
  match ":locale/*path" => 'application#set_locale'
  match "*path" => 'application#set_locale'
end

app/models/help_page.rb
class HelpPage < ActiveRecord::Base
  attr_accessible :title,
                  :identf,
                  :description,
                  :summary,
                  :blocked

  extend FriendlyId
  friendly_id :title, use: [:slugged, :simple_i18n, :history]
  include HasTranslatedSlugs

  include HasSections

  include HasTranslations
  translates :title, :summary

  validates :title, presence: true
  validates :summary, presence: true
  validates :identf, presence: true, format: { with: /\A\w+\z/ },
    length: { maximum: 30 }

end

app/controllers/help_pages_controller.rb
class HelpPagesController < ApplicationController
  respond_to :html

  expose(:help_page)

  def show

  end

  def new
    authorize! :create, HelpPage
    respond_with help_page
  end

  def create
    authorize! :create, HelpPage
    if help_page.save
      flash[:notice] = t 'help_pages.notices.created'
      respond_with help_page, location: admin_area_path
    else
      render 'new'
    end
  end

  def edit
    authorize! :update, help_page
    respond_with help_page
  end

  def update
    authorize! :update, help_page
    if help_page.save
      flash[:notice] = t 'help_pages.notices.updated'
    end
    respond_with help_page
  end

  def destroy
    authorize! :destroy, help_page
    if help_page.destroy
      flash[:notice] = t 'help_pages.notices.destroyed'
    end
  end
end

app/views/help_pages/_form.html.slim
= simple_nested_form_for help_page do |f|
  = f.error_notification

  = f.input :title, input_html: { class: 'span5' }
  = f.input :identf, input_html: { class: 'span3',
                                   maxlength: 30,
                                   disabled: help_page.blocked? }
  = f.input :blocked unless help_page.new_record?
  = f.input :description, input_html: { class: 'span5', rows: 3 }
  = f.input :summary, as: :text, input_html: { class: 'span5 rte', rows: 5 }

  = render 'section_fields', form: f

  = f.submit

app/views/help_pages/edit.html.slim
= title t('.title') + ": #{help_page.title}"

= render 'form'

- content_for :left do
  .fixed-block
    = render 'sidebar_left/form_links', document: help_page

- content_for :right do
  .right-block.help
    = render 'sidebar_right/other_translations_help', document: help_page

app/views/help_pages/new.html.slim
= title t('.title')

= render 'form'

- content_for :left do
  .fixed-block
    = render 'sidebar_left/form_links', document: help_page

app/views/help_pages/show.html.slim
= title help_page.title
= untranslated_content_message_for(help_page)

#summary
  = markdown help_page.summary

= render 'sections/index', document: help_page

- content_for :left do
  .fixed-block
    .left-block.controls.pull-right
      - if can? :update, help_page
        .control.block-row
          = link_to icon_after(:edit, t('edit')), edit_help_page_path(help_page)