config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'
require 'admin_constraint'

Masqueunacasa::Application.routes.draw do
  # CONCERNS
  concern :document do
    resource :kudos
  end

  concern :commentable do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  # PARTE SOCIAL
  resources :users, except: [:index]
  resources :groups, except: [:index] do
    resources :memberships, only: [:index, :create, :destroy]
  end

  # GENERAL

  resources :locations, only: [:index]

  match '/entrar' => 'user_sessions#new', as: :login
  match '/salir' => 'user_sessions#destroy', as: :logout
  match '/community' => 'dashboard#community', as: :community
  match '/cuatrocerocuatro' => 'dashboard#cuatrocerocuatro'
  match '/quinientos' => 'dashboard#quinientos'
  match "/enter/:id" => "users#enter", as: :enter
  get '/admin/' => 'dashboard#admin_area', as: :admin_area
  get '/search' => 'searches#show', as: :search

  root to: 'dashboard#welcome'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :password_recoveries

  # HABITAPEDIA

  resources :experiencies, concerns: [:document, :commentable]

  resources :phases, except: [:destroy] do
    resources :categories, except: [:index, :new, :create]
  end

  resources :categories, only: [:show, :new, :create], concerns: [:document, :commentable] do
    resources :proposals, only: [:new]
  end

  resources :proposals, except: [:index, :new], path: '/phases/proposals', concerns: [:document, :commentable] do
    resources :relations, only: [:new, :create, :destroy]
  end

  # ADMINISTRACIÓN

  resources :help_texts, except: [:index]
  resources :help_pages, except: [:index]

  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml', {
    prefix_on_default_locale: true }) # para permitir poner el idioma de la página
                                      # en función de las preferencias del navegador.

  # Rutas para el preview del editor de texto enriquecido
  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"

  # Ruta para la interfaz web de sidekiq
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  # Para dar soporte a las rutas antiguas, que no tenian el parámetro con el locale en
  # el idioma por defecto
  match ":locale/*path" => 'application#set_locale'
  match "*path" => 'application#set_locale'
end

app/models/group.rb
class Group < ActiveRecord::Base
  include PublicActivity::Common

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  include HasTranslations
  translates :title, :summary

  before_validation do |group|
    group.title = group.name if group.title.blank?
  end

  attr_accessible :name,
                  :title,
                  :email,
                  :avatar_image,
                  :summary,
                  :user_id,
                  :memberships_count,
                  :city, :country, :website, :twitter, :facebook
  store :settings, accessors: [:city, :country, :website,
                    :twitter, :facebook]

  validates :name, presence: true, uniqueness: true
  validates :title, presence: true
  validates :summary, presence: true
  include HasSections
  include HasLocation
  include HasPopularity


  default_scope order: 'updated_at ASC'

  belongs_to :user
  include HasMemberships

  mount_uploader :avatar_image, GroupAvatarUploader
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include ActionTracker

  respond_to :html

  expose(:groups) { Group.all }
  expose(:group)
  expose(:themes) {'textura07 negro'}
  expose(:message) { Message.new(resource: group) }

  def index
    redirect_to community_path
  end

  def show
    breadcrumb_for_group group
    respond_with group
  end

  def new
    authorize! :new, Group
    breadcrumb_for_community
  end

  def edit
    authorize! :update, group
    breadcrumb_for_group group
    respond_with group
  end

  def create
    group.user = current_user
    authorize! :create, group
    if track_action(group, :save)
      flash[:notice] = t('.created')
    end
    respond_with group
  end

  def update
    authorize! :update, group
    if track_action(group, :save)
      flash[:notice] = t('groups.notices.updated')
    end
    respond_with group
  end

  def destroy
    authorize! :destroy, group
    if track_action(group, :destroy)
      flash[:notice] = t('groups.notices.deleted')
    end
    respond_with group, location: community_path
  end
end

app/views/groups/_current.html.erb
<%= user_column 'span2' do %>
  <%= link_to avatar_image(current_group, class: 'fixed'), profile_path %>
  <div class="members">
    <% current_group.members.limit(4).each do |user| %>
      <%= link_to avatar_image(user, size: :small, class: 'fixed'), user_url(user, host: request.domain) %>
    <% end %>
  </div>
  <%= render_group_sections %>
<% end %>

app/views/groups/_form.html.slim
= simple_nested_form_for group, html: {class: 'clearfix'} do |form|
  h3 Información general

  = form.error_notification

  = form.input :new_translation, as: :hidden,
      input_html: { value: !group.translated_to?(T.l) }

  = form.input :avatar_image
  = form.input :name, hint: \
    "#{t('simple_form.hints.non_translatable_field') unless \
     group.new_record? }"
  = form.input :title, required: false
  = form.input :summary, as: :text, input_html: { rows: 8, class: 'rte' }
  = render 'section_fields', form: form
  br
  h3 Difusión
  = content_tag 'p', t('simple_form.hints.non_translatable_fields'),
    class: 'help-block' unless group.new_record?
  = form.input :email
  = form.input :website
  = form.input :twitter
  = form.input :facebook
  br

  = render 'location_fields', form: form

  = form.submit

app/views/groups/_group.html.slim
= div_for group, class: 'visor-elem no-mediafy' do
  .row
    .span3.elem-header
      h2
        span.group-icon.elem-icon
        = link_to group.title, group
    .span2
      .summary
        = markdown truncate( group.summary, length: 90, separator: ' ' )
    .span1
      = link_to avatar_image(group), group

app/views/groups/edit.html.slim
= title t('.title', group_name: group.name)
= render 'form'

- content_for :left do
  |.

app/views/groups/new.html.slim
= title t('.title')
= render 'form'

- content_for :left do
  |.

app/views/groups/show.html.slim
= title group.title
= untranslated_content_message_for(group)

- if group.website.present?
  h3 = link_to group.website, group.website

- if group.email.present?
  h4
    small correo
  = link_to group.email, "mailto:#{group.email}"

- if group.twitter.present?
  h4
    small twitter
  = link_to "#{group.twitter}", "http://twitter.com/#!#{group.twitter}", target: '_blank'

- if group.facebook.present?
  h4
    small facebook
  = link_to group.facebook, group.facebook

#summary
  = markdown group.summary

= render  'sections/index', document: group


- content_for :left do
  .fixed-block
    .left-block.controls.pull-right
      - if can? :update, group
        .control.block-row
          = link_to icon_after(:edit, t('edit')), edit_group_path(group)
      - if can? :destroy, group
        .control.block-row
          = link_to icon_after(:trash, t('delete')), group, method: :delete, confirm: t('app.confirm')
    - if group.avatar_image?
      .left-block.group-avatar-image
        = image_tag group.avatar_image, class: 'fixed'

    .left-block.group-members
      .block-header
        = t('activerecord.models.membership.other') + ":"
      - if can? :update, group
        .block-row
          = link_to icon(:plus, t('app.add', element: Membership.model_name.human)),
            group_memberships_path(group, anchor: 'add_member'),
            rel: 'new-membership'
      .block-row
        - group.members.each do |user|
          = link_to avatar_image(user, size: :small, class: 'fixed'), user_url(user)

    = render 'available_translations', document: group